// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_310_W22D_Assignment.Models;

#nullable disable

namespace SD_310_W22D_Assignment.Migrations
{
    [DbContext(typeof(MyTunesContext))]
    [Migration("20220728031355_inital")]
    partial class inital
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.Collection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("SongId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SongId");

                    b.HasIndex("UserId");

                    b.ToTable("Collection", (string)null);
                });

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nchar(50)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("ArtistId");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("CollectionId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nchar(25)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.Collection", b =>
                {
                    b.HasOne("SD_310_W22D_Assignment.Models.Song", "Song")
                        .WithMany("Collections")
                        .HasForeignKey("SongId")
                        .HasConstraintName("FK_Collection_Collection");

                    b.HasOne("SD_310_W22D_Assignment.Models.User", "User")
                        .WithMany("Collections")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Collection_Artists");

                    b.Navigation("Song");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.Song", b =>
                {
                    b.HasOne("SD_310_W22D_Assignment.Models.Artist", "Artist")
                        .WithMany("Songs")
                        .HasForeignKey("ArtistId")
                        .IsRequired()
                        .HasConstraintName("FK_Songs_Songs");

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.User", b =>
                {
                    b.HasOne("SD_310_W22D_Assignment.Models.Collection", "Collection")
                        .WithMany("Users")
                        .HasForeignKey("CollectionId")
                        .HasConstraintName("FK_Users_Collection");

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.Artist", b =>
                {
                    b.Navigation("Songs");
                });

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.Collection", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.Song", b =>
                {
                    b.Navigation("Collections");
                });

            modelBuilder.Entity("SD_310_W22D_Assignment.Models.User", b =>
                {
                    b.Navigation("Collections");
                });
#pragma warning restore 612, 618
        }
    }
}
